package snapshot

// Golden conformance: fixtures generated by edge-analyst/scripts/gen-fixtures.mjs, with expected
// outputs computed by running the reference implementation (src/blocklist.js) itself. A failure
// here means the port drifted from the format owner — fix the port, never the fixture. This is
// the Go twin of camada-core/test/conformance.test.ts, case for case.

import (
	"encoding/json"
	"reflect"
	"testing"

	"github.com/camada/camada-go/internal/testutil"
)

type caseInput struct {
	IP      string            `json:"ip"`
	ASN     int               `json:"asn"`
	Country string            `json:"country"`
	TLSX    string            `json:"tlsx"`
	Path    string            `json:"path"`
	UA      string            `json:"ua"`
	Headers map[string]string `json:"headers"`
}

type goldenCase struct {
	Input  caseInput      `json:"input"`
	Expect map[string]any `json:"expect"`
}

func cases3(t *testing.T) map[string]map[string][]goldenCase {
	var c map[string]map[string][]goldenCase
	testutil.ReadJSON(t, "blk3/cases.json", &c)
	return c
}

func cases5(t *testing.T) map[string][]goldenCase {
	var c map[string]map[string][]goldenCase
	testutil.ReadJSON(t, "blk5/cases.json", &c)
	return c["v5"]
}

func matcher(t *testing.T, name, dir string) *Matcher {
	t.Helper()
	meta, err := DecodeMeta(testutil.ReadBin(t, dir+"/"+name+".meta.json"))
	if err != nil {
		t.Fatalf("meta %s: %v", name, err)
	}
	snap, err := ParseSnapshot(testutil.ReadBin(t, dir+"/"+name+".bin"), meta)
	if err != nil {
		t.Fatalf("parse %s: %v", name, err)
	}
	return NewMatcher(snap)
}

// asInput: a v5 case's `headers` is a map with already lower-cased keys — the request as the tap
// sees it. It becomes the header(name) getter §D3 defines, exactly as the reference harness does.
func asInput(c goldenCase) MatchInput {
	i := blindInput(c)
	if c.Input.Headers != nil {
		h := c.Input.Headers
		i.Header = func(n string) (string, bool) { v, ok := h[n]; return v, ok }
	}
	return i
}

func blindInput(c goldenCase) MatchInput {
	return MatchInput{IP: c.Input.IP, ASN: c.Input.ASN, Country: c.Input.Country, TLSX: c.Input.TLSX, Path: c.Input.Path, UA: c.Input.UA}
}

func nullable(s string) any {
	if s == "" {
		return nil
	}
	return s
}

// the reference reports "nothing matched" as reason null; the port leaves it "" and the outcome maps it back
func outcome(r MatchResult) map[string]any {
	return map[string]any{"block": r.Block, "challenge": r.Challenge, "allowed": r.Allowed, "reason": nullable(r.Reason)}
}

func outcome5(r MatchResult) map[string]any {
	o := outcome(r)
	o["warn"], o["action"], o["rule"] = r.Warn, nullable(r.Action), nullable(r.Rule)
	return o
}

func label(c goldenCase) string {
	b, _ := json.Marshal(c.Input)
	return string(b)
}

func TestV3V4(t *testing.T) {
	all := cases3(t)
	for _, version := range []string{"v3", "v4"} {
		t.Run(version+"/basic", func(t *testing.T) {
			m := matcher(t, version+"-basic", "blk3")
			for _, c := range all[version]["basic"] {
				if got := outcome(m.Match(asInput(c))); !reflect.DeepEqual(got, c.Expect) {
					t.Errorf("%s: got %v want %v", label(c), got, c.Expect)
				}
			}
		})
		t.Run(version+"/empty", func(t *testing.T) {
			m := matcher(t, version+"-empty", "blk3")
			for _, c := range all[version]["empty"] {
				if got := outcome(m.Match(asInput(c))); !reflect.DeepEqual(got, c.Expect) {
					t.Errorf("%s: got %v want %v", label(c), got, c.Expect)
				}
			}
		})
	}
}

func flags(r MatchResult) int {
	n := 0
	for _, b := range []bool{r.Allowed, r.Block, r.Challenge, r.Warn} {
		if b {
			n++
		}
	}
	return n
}

func TestV4Outcomes(t *testing.T) {
	all := cases3(t)
	t.Run("never two outcome flags", func(t *testing.T) {
		m := matcher(t, "v4-basic", "blk3")
		for _, c := range append(all["v4"]["basic"], all["v4"]["empty"]...) {
			if flags(m.Match(asInput(c))) > 1 {
				t.Errorf("%s: two flags", label(c))
			}
		}
	})
	t.Run("v3 container cannot express allow or challenge", func(t *testing.T) {
		v3 := matcher(t, "v3-basic", "blk3")
		v4c, v3c := all["v4"]["basic"], all["v3"]["basic"]
		if len(v4c) != len(v3c) {
			t.Fatalf("case lists differ: %d vs %d", len(v4c), len(v3c))
		}
		diverged := 0
		for i := range v4c {
			if reflect.DeepEqual(v4c[i].Expect, v3c[i].Expect) {
				continue
			}
			diverged++
			if got := outcome(v3.Match(asInput(v4c[i]))); !reflect.DeepEqual(got, v3c[i].Expect) {
				t.Errorf("%s: got %v want %v", label(v4c[i]), got, v3c[i].Expect)
			}
		}
		if diverged == 0 {
			t.Fatal("the fixtures must actually exercise the new sections")
		}
	})
}

func TestV5(t *testing.T) {
	c5 := cases5(t)
	t.Run("rules", func(t *testing.T) {
		m := matcher(t, "v5-rules", "blk5")
		for _, c := range c5["rules"] {
			if got := outcome5(m.Match(asInput(c))); !reflect.DeepEqual(got, c.Expect) {
				t.Errorf("%s: got %v want %v", label(c), got, c.Expect)
			}
		}
	})
	t.Run("empty", func(t *testing.T) {
		m := matcher(t, "v5-empty", "blk5")
		for _, c := range c5["empty"] {
			if got := outcome5(m.Match(asInput(c))); !reflect.DeepEqual(got, c.Expect) {
				t.Errorf("%s: got %v want %v", label(c), got, c.Expect)
			}
		}
	})
	t.Run("never two outcome flags", func(t *testing.T) {
		m := matcher(t, "v5-rules", "blk5")
		for _, c := range append(c5["rules"], c5["empty"]...) {
			if flags(m.Match(asInput(c))) > 1 {
				t.Errorf("%s: two flags", label(c))
			}
		}
	})
	t.Run("names the rule only when a rule decided", func(t *testing.T) {
		m := matcher(t, "v5-rules", "blk5")
		for _, c := range c5["rules"] {
			r := m.Match(asInput(c))
			if r.Reason == "rule" && (r.Rule == "" || r.Action == "") {
				t.Errorf("%s: rule decided without naming itself: %+v", label(c), r)
			}
			if r.Reason != "rule" && (r.Rule != "" || r.Action != "") {
				t.Errorf("%s: a side decided but a rule is named: %+v", label(c), r)
			}
		}
	})
	t.Run("rules overrule the sides a v4 container can only read", func(t *testing.T) {
		v4, rules := matcher(t, "v4-basic", "blk3"), matcher(t, "v5-rules", "blk5")
		diverged := 0
		for _, c := range c5["rules"] {
			if reflect.DeepEqual(outcome(v4.Match(asInput(c))), outcome(rules.Match(asInput(c)))) {
				continue
			}
			diverged++
			if c.Expect["reason"] != "rule" {
				t.Errorf("%s: diverged without a rule: %v", label(c), c.Expect)
			}
		}
		if diverged == 0 {
			t.Fatal("no divergence between v4 and v5")
		}
	})
	t.Run("header cases decide through the getter alone", func(t *testing.T) {
		m := matcher(t, "v5-rules", "blk5")
		n := 0
		for _, c := range c5["rules"] {
			if len(c.Input.Headers) == 0 {
				continue
			}
			n++
			if got := outcome5(m.Match(asInput(c))); !reflect.DeepEqual(got, c.Expect) {
				t.Errorf("%s: got %v want %v", label(c), got, c.Expect)
			}
			blind := m.Match(blindInput(c)) // no getter: a header condition can never fire (fail open)
			if c.Expect["reason"] == "rule" {
				if blind.Rule == c.Expect["rule"] {
					t.Errorf("%s: fired blind", label(c))
				}
			} else if nullable(blind.Reason) != c.Expect["reason"] {
				t.Errorf("%s: blind reason %q want %v", label(c), blind.Reason, c.Expect["reason"])
			}
		}
		if n == 0 {
			t.Fatal("no header cases")
		}
	})
}

func TestInterleavedMatchersKeepStateApart(t *testing.T) {
	a, b := matcher(t, "v4-basic", "blk3"), matcher(t, "v4-empty", "blk3")
	for i := 0; i < 20; i++ {
		if a.Match(MatchInput{IP: "2001:db8::1"}).Reason != "ip6" {
			t.Fatal("a lost its ip6 block")
		}
		if b.Match(MatchInput{IP: "2001:db8::1"}).Block {
			t.Fatal("b blocked")
		}
		if a.Match(MatchInput{IP: "2001:db8::2"}).Block {
			t.Fatal("a blocked a neighbour")
		}
	}
}
